name: ACEest CI Pipeline

on:
  push:
    branches: 
      - main
      - release/*
      - feature-*
    tags:
      - 'v*.*.*'
  pull_request:
    branches: 
      - main

  workflow_dispatch:
      inputs:
        tag:
          description: 'Tag To Deploy'
          required: true
        deployment_strategy:
          description: 'Deployment Strategy ( rolling, blue-green, canary | shadow)'
          required: true
          default: rolling
  

jobs:

  build-and-lint:
    name: Build and Lint ( Sonar Qube Scan ) 
    runs-on: self-hosted

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag || github.ref }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=aceest
            -Dsonar.sources=.
            -Dsonar.exclusions=tests/**
            -Dsonar.python.coverage.reportPaths=coverage.xml
            
      - name: SonarQube Quality Gate Check
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
         echo "Waiting for SonarQube Quality Gate..."

          STATUS="PENDING"    
          echo "Host URL: ${{ secrets.SONAR_HOST_URL }}"
          echo "Token length: ${#SONAR_TOKEN}"
              
            RESPONSE=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
              "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=aceest")
            STATUS=$(echo "$RESPONSE" | jq -r '.projectStatus.status' 2>/dev/null)
          if [ "$STATUS" != "OK" ]; then
            echo " Quality Gate FAILED"
            exit 1
          fi
      
          echo "Quality Gate PASSED"
          



  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: build-and-lint

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag || github.ref }}

      - name: Build Docker Image
        run: |
          docker build -t aceest-test:${{ contains(github.ref, 'feature/') && github.sha || 'latest' }} .



  automated-testing:
    name: Automated Testing
    runs-on: ubuntu-latest
    needs: docker-build

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
            ref: ${{ github.event.inputs.tag || github.ref }}

      - name: Build Test Docker Image
        run: |
          docker build -t aceest-test -f test.Dockerfile .

      - name: Run Test and Generate Coverage
        run: |
          docker run --rm \
          -v ${{ github.workspace }}:/app \
          aceest-test

      - name: Verify Coverage Files
        run: |
          ls -R

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            ./coverage.xml
            ./htmlcov/
            
  jenkins-trigger-and-wait:
    runs-on: self-hosted
    needs: [build-and-lint, docker-build, automated-testing]

    steps:
      - name: Trigger and Wait for Jenkins
        run: |
          QUEUE_URL=$(curl -i -X POST "http://localhost:8081/job/accest-build-multibranch/job/${{ github.head_ref || github.ref_name }}/build" \
          --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" \
          | grep -i Location | awk '{print $2}' | tr -d '\r')

          echo "Queue URL: $QUEUE_URL"

          # Wait for build to start
          while true; do
            BUILD_URL=$(curl -s "$QUEUE_URL/api/json" \
              --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" | jq -r '.executable.url')

            if [ "$BUILD_URL" != "null" ]; then
              break
            fi

            sleep 3
          done

          echo "Build URL: $BUILD_URL"

          # Wait for completion
          while true; do
            RESULT=$(curl -s "${BUILD_URL}api/json" \
              --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" | jq -r '.result')

            if [ "$RESULT" != "null" ]; then
              break
            fi

            sleep 5
          done

          echo "Result: $RESULT"

          if [ "$RESULT" != "SUCCESS" ]; then
            exit 1
          fi


  push-dev-latest:
    name: Push Docker Image (Only Tags)
    runs-on: ubuntu-latest
    needs: [jenkins-trigger-and-wait]
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag || github.ref }}

      - name: Get Latest Git Tag
        id: get_tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TAG=${{ github.event.inputs.tag }}
          else
            TAG=${GITHUB_REF#refs/tags/}
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t plsphaniteja2024tm93573/aceest-web-app-2024tm93573:$TAG .

      - name: Push Docker Image
        run: |
          docker push plsphaniteja2024tm93573/aceest-web-app-2024tm93573:$TAG

  
  deploy-to-kubernetes:
    name: Deploy to Kubernetes (Only Tags and Manual Trigger)
    runs-on: self-hosted
    needs: [jenkins-trigger-and-wait]
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set Tag and Deployment Strategy
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TAG=${{ github.event.inputs.tag }}
            DEPLOYMENT_STRATEGY=${{ github.event.inputs.deployment_strategy }}
          else
            TAG=${GITHUB_REF#refs/tags/}
            DEPLOYMENT_STRATEGY="rolling"
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "DEPLOYMENT_STRATEGY=$DEPLOYMENT_STRATEGY" >> $GITHUB_ENV
      - name: Set Kubernetes Context
        run: | 
          kubectl config use-context minikube

      - name: Deploy Based on Strategy
        run: |
          echo "Using strategy: $DEPLOYMENT_STRATEGY"

          if [ "$DEPLOYMENT_STRATEGY" = "blue-green" ]; then

            CURRENT=$(kubectl get svc aceest-service -o jsonpath='{.spec.selector.version}')
    
            if [ -z "$CURRENT" ]; then
              echo "No existing deployment. Defaulting BLUE"
              CURRENT="none"
              TARGET="blue"
            elif [ "$CURRENT" = "blue" ]; then
              TARGET="green"
            else
              TARGET="blue"
            fi

            echo "Current: $CURRENT"
            echo "Target: $TARGET"

            kubectl apply -f Deployment/blue-green-deployment/

            kubectl set image deployment/aceest-$TARGET \
            aceest-container=plsphaniteja2024tm93573/aceest-web-app-2024tm93573:$TAG

            kubectl rollout status deployment/aceest-$TARGET

            kubectl patch service aceest-service \
            -p "{\"spec\":{\"selector\":{\"app\":\"aceest\",\"version\":\"$TARGET\"}}}"

          elif [ "$DEPLOYMENT_STRATEGY" = "canary" ]; then

            echo "Canary Deployment"

            kubectl apply -f Deployment/canary-deployment/

            kubectl set image deployment/aceest-canary \
            aceest-container=plsphaniteja2024tm93573/aceest-web-app-2024tm93573:$TAG

            kubectl rollout status deployment/aceest-canary

          elif [ "$DEPLOYMENT_STRATEGY" = "shadow" ]; then

            echo "Shadow Deployment"

            kubectl apply -f Deployment/shadow-deployment/

            kubectl set image deployment/aceest-shadow \
            aceest-container=plsphaniteja2024tm93573/aceest-web-app-2024tm93573:$TAG

          else

            echo "🔄 Rolling Deployment"

            kubectl apply -f Deployment/base-deployment/deployment.yaml
            kubectl apply -f Deployment/base-deployment/service.yaml

            kubectl set image deployment/aceest-app \
            aceest-container=plsphaniteja2024tm93573/aceest-web-app-2024tm93573:$TAG

            kubectl rollout status deployment/aceest-app

          fi
            